docker:
  image: kerelape/docker-image:go
merge:
  script: |-
    go test ./...
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    go test ./...
    git commit -am "${tag}"